### ISSUE TITLE
New Case Study: SmallStep

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/sigstore-blog#30]
A new case study from SmallStep for approval. Please review/comment in Google doc and then will convert to a PR once ready to post. 

https://docs.google.com/document/d/1uJIHSVyRq1DeJnp3VJY3aGL4qMEdVDTORjzPnYCxzNk/edit

**Comment by haydentherapper** [comment]
Published in https://github.com/sigstore/sigstore-blog/blob/main/content/case-study-smallstep.md
