### ISSUE TITLE
Update Sigstore Blog Logo + Favicon

### ISSUE THREAD

**Issue by zestyroxy** [sigstore/sigstore-blog#33]
**Description**

Sigstore has a new logo. I'm not sure who made the blog logo? New artwork is [available here](https://blog.sigstore.dev/).
![image](https://user-images.githubusercontent.com/18251881/232085325-b1ffbc28-8df8-438d-8115-6d8565e3f445.png)

**Favicon**
And attaching the favicon here. The designer didn't provide an .ico file, let me know if you need that.
![sigstore_favicon](https://user-images.githubusercontent.com/18251881/232085131-09ba2047-4de3-49c5-b619-6d310d70d999.png)

**Comment by haydentherapper** [comment]
Completed this a little while ago
