### ISSUE TITLE
Set up reviewers

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-blog#5]
We need to set up approvals / reviews from the TSC team

Some sort of quorum if possible (?) , 3 out of 5 or do we want 5/5?

@trevrosen @bobcallaway @priyawadhwa @SantiagoTorres 

cc @cpanato for backend magicness.

**Comment by lukehinds** [comment]
I reckon 3/5 as well, unless its a bit spicy and then the TSC can air on the side of caution and await more consensus.

**Comment by SantiagoTorres** [comment]
I think 3/5 makes sense.

**Comment by priyawadhwa** [comment]
3/5 sgtm

**Comment by cpanato** [comment]
3/5 sgtm as well

**Comment by lukehinds** [comment]
@rchaganti could you let me know how the digits on the end of the markdown files is generated:

a-guide-to-running-sigstore-locally-**f312dfac0682**.md

**Comment by rchaganti** [comment]
@lukehinds that was an artefact from migrating posts from medium. We don't need that. I left it there in the URL to make sure we don't break SEO or links.

**Comment by cpanato** [comment]
PRs are in place to configure this behavior

**Comment by haydentherapper** [comment]
This was completed back in Feb
