### ISSUE TITLE
What is the format of the name of the file for a new blog entry?

### ISSUE THREAD

**Issue by mathieu-benoit** [sigstore/sigstore-blog#6]
What is the format of the name of the file for a new blog entry?

For example: `a-guide-to-running-sigstore-locally-f312dfac0682.md`, what does `f312dfac0682` represent? I want to create a new blog article, how to generate this value?

**Comment by lukehinds** [comment]
@rchaganti ^

**Comment by rchaganti** [comment]
@mathieu-benoit don't worry about that. It was part of the migration from old blog. You can name it whatever-you-want.md. Please make sure you use the front matter from an old article and update it as needed. I will create a contribution guide today to layout the steps to author a new article.

**Comment by mathieu-benoit** [comment]
Gotcha, thanks, will do!
